build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.18
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.18
codenotary:
  signer: 11554546+thomasddn@users.noreply.github.com
  base_image: notary@home-assistant.io
