name: QBHA
description: Qbus bridge for Home Assistant
version: 0.7.1
image: thomasddn/home-assistant-addon-qbha-{arch}
slug: qbha
codenotary: 11554546+thomasddn@users.noreply.github.com
init: false
arch:
  - aarch64
  - amd64
services:
  - 'mqtt:need'
map:
  - addon_config:rw
options:
  BINARY_SENSORS: ""
  CLIMATE_PRESETS: "MANUEEL,VORST,NACHT,ECONOMY,COMFORT"
  CLIMATE_SENSORS: false
  QBUS_CAPTURE: false
  LOG_LEVEL: INFO
schema:
  MQTT_HOST: str?
  MQTT_PORT: port?
  MQTT_USER: str?
  MQTT_PWD: str?
  BINARY_SENSORS: str?
  CLIMATE_PRESETS: str?
  CLIMATE_SENSORS: bool
  QBUS_CAPTURE: bool
  LOG_LEVEL: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)
