build_from:
  armv7: ghcr.io/home-assistant/armv7-base-ubuntu:20.04
  amd64: ghcr.io/home-assistant/amd64-base-ubuntu:20.04
codenotary:
  signer: 11554546+thomasddn@users.noreply.github.com
  base_image: notary@home-assistant.io
