build_from:
  aarch64: ghcr.io/home-assistant/base-debian:trixie
  amd64: ghcr.io/home-assistant/base-debian:trixie
codenotary:
  signer: 11554546+thomasddn@users.noreply.github.com
  base_image: notary@home-assistant.io
