name: Qbus MQTT Gateway
description: Publishes Qbus states and events to MQTT
version: 0.1.0
image: thomasddn/home-assistant-addon-qbusmqtt-{arch}
slug: qbusmqtt
init: false
codenotary: 11554546+thomasddn@users.noreply.github.com
host_network: true
arch:
  - amd64
  - armv7
services:
  - 'mqtt:need'
schema:
  MQTT_HOST: str?
  MQTT_PORT: port?
  MQTT_USER: str?
  MQTT_PWD: str?
