name: Test Home Assistant builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Test build
        # uses: home-assistant/builder@54dcff2fc94a5c8b71abe3a94ea574dc77895554
        uses: home-assistant/builder@2023.09.0
        with:
          args: |
            --test \
            --all \
            --target qbha \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}
