name: HA Addon Builder - Push qbha

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1
        
      - name: Docker Login
        # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Push qbha
        # uses: home-assistant/builder@54dcff2fc94a5c8b71abe3a94ea574dc77895554
        uses: home-assistant/builder@2023.09.0
        with:
          args: |
            --all \
            --target qbha \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}
