name: Test Home Assistant builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Test build armhf
        # uses: home-assistant/builder@54dcff2fc94a5c8b71abe3a94ea574dc77895554
        uses: home-assistant/builder@2023.09.0
        with:
          args: |
            --test \
            --armhf \
            --target qbha \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}
        
      - name: Test build armv7
        # uses: home-assistant/builder@54dcff2fc94a5c8b71abe3a94ea574dc77895554
        uses: home-assistant/builder@2023.09.0
        with:
          args: |
            --test \
            --armv7 \
            --target qbha \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}
        
      - name: Test build amd64
        # uses: home-assistant/builder@54dcff2fc94a5c8b71abe3a94ea574dc77895554
        uses: home-assistant/builder@2023.09.0
        with:
          args: |
            --test \
            --amd64 \
            --target qbha \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}
        
      - name: Test build aarch64
        # uses: home-assistant/builder@54dcff2fc94a5c8b71abe3a94ea574dc77895554
        uses: home-assistant/builder@2023.09.0
        with:
          args: |
            --test \
            --aarch64 \
            --target qbha \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}
        
      - name: Test build i386
        # uses: home-assistant/builder@54dcff2fc94a5c8b71abe3a94ea574dc77895554
        uses: home-assistant/builder@2023.09.0
        with:
          args: |
            --test \
            --i386 \
            --target qbha \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}
