name: HA Addon - Push qbusmqtt

on:
  workflow_dispatch:

env:
  ARCHITECTURES: '["amd64", "aarch64"]'
  IMAGE_NAME: home-assistant-addon-qbusmqtt

permissions:
  contents: read

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      version: ${{ steps.info.outputs.version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: Get app information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./qbusmqtt"

      - name: Prepare build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.IMAGE_NAME }}
          registry-prefix: docker.io/${{ secrets.DOCKER_USERNAME }}

  build:
    name: Build ${{ matrix.arch }} image
    needs: init
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: Build image
        uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          arch: ${{ matrix.arch }}
          container-registry: docker.io
          container-registry-username: ${{ secrets.DOCKER_USERNAME }}
          container-registry-password: ${{ secrets.DOCKER_TOKEN }}
          context: "./qbusmqtt"
          cosign: "false"
          image: ${{ matrix.image }}
          image-tags: |
            ${{ needs.init.outputs.version }}
            latest
          push: "true"
          version: ${{ needs.init.outputs.version }}

  manifest:
    name: Publish multi-arch manifest
    needs: [init, build]
    runs-on: ubuntu-latest
    steps:
      - name: Publish multi-arch manifest
        uses: home-assistant/builder/actions/publish-multi-arch-manifest@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          container-registry: docker.io
          container-registry-username: ${{ secrets.DOCKER_USERNAME }}
          container-registry-password: ${{ secrets.DOCKER_TOKEN }}
          cosign: "false"
          image-name: ${{ env.IMAGE_NAME }}
          image-tags: |
            ${{ needs.init.outputs.version }}
            latest
          registry-prefix: docker.io/${{ secrets.DOCKER_USERNAME }}
