name: HA Addon - Push qbusmqtt

on:
  workflow_dispatch:

jobs:
  build:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1
        
      - name: Docker Login
        # uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Push qbusmqtt
        # uses: home-assistant/builder@cebacc797363e17696b5649799bdaadd7b7f5d70
        uses: home-assistant/builder@2024.03.5
        with:
          args: |
            --all \
            --target qbusmqtt \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}
